services:
  frontend:
    ports:
      - '8428:80'
      - '3542:3000'
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: final
    depends_on:
      - 'backend'
    environment:
      - 'API_URL=http://localhost:5000'
      - 'CLIENT_URL=http://localhost'
    volumes:
      - ./frontend:/app

  backend:
    ports:
      - '5000:5000'
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - .upload/:/usr/src/app/src/upload
      - ./backend/src/:/usr/src/app/src
