version: "3.8"
services:
    frontend:
        image: vallezw/image-uploader-client
        ports:
            - "80:80"
        environment:
            - "API_URL=http://localhost:5000"
            - "CLIENT_URL=http://localhost"
        container_name: "frontend"
        
    backend:
        image: vallezw/image-uploader-backend 
        ports:
            - "5000:5000"

